### ISSUE TITLE
commercial plugins distributed

### ISSUE THREAD

**Issue by unitycoder** [nimdanet/Line-Art#1]
Hi,

Can you please remove the commercial plugins from this repository:
mobilepaint:
*

If you want to use version control, use bitbucket.org, they have free private repositories.

thanks!

**Comment by uemin** [comment]
Hi,

I needed help of a friend for mac build, so I put the project on git just to share with him. I forgot your asset was a commercial one, sorry :(. I deleted the repo.

Take care

**Comment by uemin** [comment]
Meanwhile, I think there a confision with the github link you provided. nimdanet is not my user name. I removed the funnyColors repo.

**Comment by unitycoder** [comment]
Thanks! yeah, pasted the wrong link (it was in there also)
(And no probs, check bitbucket.org for the free private repo hosting)

*this issue can be deleted
